language: go

go:
  - 1.9.x
  - tip

before_install:
  - go get -t -v ./...

script:
  - go test github.com/langhuihui/RxGo/unit_tests -coverpkg=github.com/langhuihui/RxGo/... -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)