language: go

go:
  - 1.9.x
  - tip

before_install:
  - go get -t -v ./...

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash) -t 6e9d8ea6-c526-4e8e-b1e0-2f8dc4d58eeb